method: grid
metric:
  goal: maximize
  name: normalized_score_mean
parameters:
  actor_lr:
    values:
      - 0.0003
      - 0.0001
      - 0.00003
  frame_stack:
    values:
      - 1
      - 8
  include_previous_action:
    values:
      - True
      - False
program: algorithms/bc.py

command:
  - python
  - ${program}
  - train
  - hp_sweeps/bc_sweep_config.yaml
