method: grid
metric:
  goal: maximize
  name: normalized_score_mean
parameters:
  gamma:
    values:
      - 0.1
      - 0.5
      - 0.9
  qf_lr:
    values:
      - 0.0001
      - 0.00003
  frame_stack:
    values:
      - 1
      - 8
  include_previous_action:
    values:
      - True
      - False
program: algorithms/dqn.py

command:
  - python
  - ${program}
  - train
  - hp_sweeps/dqn_restriction_config.yaml
